codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%
        threshold: 1%
    patch:
      default:
        target: 50%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "examples/**/*"
  - "**/mock/**"
  - "**/mocks/**" 